spring.application.name=url-shortener-springboot
server.port=${PORT:8080}
# MySQL Database Config (Commented out)
# spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
# spring.datasource.username=root
# spring.datasource.password=root@123
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Supabase PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://db.pecgtnrztplxvggtwjuj.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Supabase@7482
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=Y2hvb25nLWRldmVsb3BtZW50LXNlY3JldC1rZXktMjg0NzYtY29tcGxldGUtcHJvamVjdC1zdXBhYmFzZQ==
jwt.expiration=172800000
frontend.url=http://localhost:5173